In [0]:
import tensorflow as tf 
tf.test.gpu_device_name()

''

In [0]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (0.25.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.6.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.17.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)

In [0]:
import pandas as pd

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import io 
df2 = pd.read_csv('/content/drive/My Drive/sensor.csv')

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import preprocessing

In [0]:
train_df = pd.read_csv('/content/drive/My Drive/sensor.csv', header=0)
train_df.drop(train_df.columns[[17]], axis=1, inplace=True)

In [0]:
train_df

        Unnamed: 0            timestamp  ...  sensor_51  machine_status
0                0  2018-04-01 00:00:00  ...   201.3889          NORMAL
1                1  2018-04-01 00:01:00  ...   201.3889          NORMAL
2                2  2018-04-01 00:02:00  ...   203.7037          NORMAL
3                3  2018-04-01 00:03:00  ...   203.1250          NORMAL
4                4  2018-04-01 00:04:00  ...   201.3889          NORMAL
...            ...                  ...  ...        ...             ...
220315      220315  2018-08-31 23:55:00  ...   231.1921          NORMAL
220316      220316  2018-08-31 23:56:00  ...   231.1921          NORMAL
220317      220317  2018-08-31 23:57:00  ...   232.0602          NORMAL
220318      220318  2018-08-31 23:58:00  ...   234.0856          NORMAL
220319      220319  2018-08-31 23:59:00  ...   234.0856          NORMAL

[220320 rows x 54 columns]

In [0]:
'''
for i in range(2,54):
  #target = train_df[i]
  target = train_df.iloc[:, i]
  print(target)
  train_df = train_df.assign(InterpolateSLinear=train_df.target.interpolate(method='slinear'))
'''
train_df = train_df.interpolate(method ='slinear', limit_direction ='forward') 
train_df['sensor_01'][27200]
#train_df[1]

38.3680534362793

In [0]:
train_df.head()

   Unnamed: 0            timestamp  ...  sensor_51  machine_status
0           0  2018-04-01 00:00:00  ...   201.3889          NORMAL
1           1  2018-04-01 00:01:00  ...   201.3889          NORMAL
2           2  2018-04-01 00:02:00  ...   203.7037          NORMAL
3           3  2018-04-01 00:03:00  ...   203.1250          NORMAL
4           4  2018-04-01 00:04:00  ...   201.3889          NORMAL

[5 rows x 54 columns]

In [0]:
k = 0
for i in range(len(train_df)):
    if(train_df["machine_status"][i] == "BROKEN" or i==(len(train_df)-1)):
        print("Hi")
        count = 0
        for j in range(i,k-1,-1):
            train_df.at[j,'RUL']= count
            count = count + 1
        k = i

Hi
Hi
Hi
Hi
Hi
Hi
Hi
Hi

In [0]:
train_df

        Unnamed: 0            timestamp  ...  machine_status      RUL
0                0  2018-04-01 00:00:00  ...          NORMAL  17155.0
1                1  2018-04-01 00:01:00  ...          NORMAL  17154.0
2                2  2018-04-01 00:02:00  ...          NORMAL  17153.0
3                3  2018-04-01 00:03:00  ...          NORMAL  17152.0
4                4  2018-04-01 00:04:00  ...          NORMAL  17151.0
...            ...                  ...  ...             ...      ...
220315      220315  2018-08-31 23:55:00  ...          NORMAL      4.0
220316      220316  2018-08-31 23:56:00  ...          NORMAL      3.0
220317      220317  2018-08-31 23:57:00  ...          NORMAL      2.0
220318      220318  2018-08-31 23:58:00  ...          NORMAL      1.0
220319      220319  2018-08-31 23:59:00  ...          NORMAL      0.0

[220320 rows x 55 columns]

In [0]:
train_df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [0]:
train_df.head()

             timestamp  sensor_00  sensor_01  ...  sensor_51  machine_status      RUL
0  2018-04-01 00:00:00   2.465394   47.09201  ...   201.3889          NORMAL  17155.0
1  2018-04-01 00:01:00   2.465394   47.09201  ...   201.3889          NORMAL  17154.0
2  2018-04-01 00:02:00   2.444734   47.35243  ...   203.7037          NORMAL  17153.0
3  2018-04-01 00:03:00   2.460474   47.09201  ...   203.1250          NORMAL  17152.0
4  2018-04-01 00:04:00   2.445718   47.13541  ...   201.3889          NORMAL  17151.0

[5 rows x 54 columns]

In [0]:
train_df.drop(['machine_status'], axis=1, inplace=True)

In [0]:
for col in train_df.columns[1:-1]:
    train_df[col] = train_df[col].fillna(train_df[col].mean())

In [0]:
rul_csv = train_df.to_csv (r'rul_csv.csv', index = None, header=True)

In [0]:
train_df

                  timestamp  sensor_00  ...  sensor_51      RUL
0       2018-04-01 00:00:00   2.465394  ...   201.3889  17155.0
1       2018-04-01 00:01:00   2.465394  ...   201.3889  17154.0
2       2018-04-01 00:02:00   2.444734  ...   203.7037  17153.0
3       2018-04-01 00:03:00   2.460474  ...   203.1250  17152.0
4       2018-04-01 00:04:00   2.445718  ...   201.3889  17151.0
...                     ...        ...  ...        ...      ...
220315  2018-08-31 23:55:00   2.407350  ...   231.1921      4.0
220316  2018-08-31 23:56:00   2.400463  ...   231.1921      3.0
220317  2018-08-31 23:57:00   2.396528  ...   232.0602      2.0
220318  2018-08-31 23:58:00   2.406366  ...   234.0856      1.0
220319  2018-08-31 23:59:00   2.396528  ...   234.0856      0.0

[220320 rows x 53 columns]

In [0]:
from sklearn.decomposition import PCA

train_df_pca = train_df
#train_df_pca.drop(['timestamp'], axis=1, inplace=True)
print(train_df_pca.head())
pca = PCA(n_components= 20)
arr = pca.fit_transform(train_df_pca.values)
print(len(arr[0]))

   sensor_00  sensor_01  sensor_02  ...  sensor_50  sensor_51      RUL
0   2.465394   47.09201    53.2118  ...   243.0556   201.3889  17155.0
1   2.465394   47.09201    53.2118  ...   243.0556   201.3889  17154.0
2   2.444734   47.35243    53.2118  ...   241.3194   203.7037  17153.0
3   2.460474   47.09201    53.1684  ...   240.4514   203.1250  17152.0
4   2.445718   47.13541    53.2118  ...   242.1875   201.3889  17151.0

[5 rows x 52 columns]
20

In [0]:
from pandas import read_csv, DataFrame
from numpy.random import seed
from sklearn.preprocessing import minmax_scale
from sklearn.model_selection import train_test_split
from keras.layers import Input, Dense
from keras.models import Model

Using TensorFlow backend.

In [0]:
Y = train_df['RUL']
X = train_df.iloc[:, 1:52]
X.head()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.5, random_state = seed(2017))

In [0]:
X_test.head()

        sensor_01  sensor_02  sensor_03  ...   sensor_50  sensor_51      RUL
209220  49.522570   51.25868  45.789928  ...  183.046321   222.5116  11099.0
56475   47.526039   52.90799  44.531250  ...  187.210600   211.2269  12843.0
5395    48.567710   51.73611  44.661457  ...  258.680500   239.8727  11760.0
85784   49.913190   54.68750  44.531250  ...  250.578700   217.5926  42256.0
44522   46.614580   51.86632  43.185760  ...  184.317100   186.3426  24796.0

[5 rows x 51 columns]

In [0]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = X_train
# y = 1 * x_0 + 2 * x_1 + 3
Y = Y_train
reg = LinearRegression().fit(X, Y)
reg.score(X, Y)

reg.coef_

reg.intercept_

# reg.predict(np.array([[3, 5]]))
# print(encoded_out,len(encoded_out))

-44131.44457449495

In [0]:
from sklearn.svm import SVR


regressor=SVR(kernel='linear',degree=1)
regressor.fit(X_train,Y_train)
pred=regressor.predict(xtest)



regressor=SVR(kernel='rbf',epsilon=1.0)
regressor.fit(X_train,Y_train)
pred=regressor.predict(xtest)

In [0]:
reg.predict(X_test)

array([ 9234.21657712,  9307.88275785, 24593.25165676, ...,
       23169.99904847, 19597.94126743, 10064.73779967])

In [0]:
Y_test

209220    11099.0
56475     12843.0
5395      11760.0
85784     42256.0
44522     24796.0
           ...
135072     6059.0
18852      5658.0
44749     24569.0
145771    20669.0
62678      6640.0
Name: RUL, Length: 110160, dtype: float64

In [0]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(X)

X_train = []
y_train = []
for i in range(60, 2035):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

print(X_train)

[[[9.85719980e-01]
  [9.63334871e-01]
  [9.69509803e-01]
  ...
  [9.82246483e-01]
  [9.84947917e-01]
  [1.08173128e-02]]

 [[9.63334871e-01]
  [9.69509803e-01]
  [9.62562809e-01]
  ...
  [9.84947917e-01]
  [1.08173128e-02]
  [9.18178230e-01]]

 [[9.69509803e-01]
  [9.62562809e-01]
  [7.71902962e-04]
  ...
  [1.08173128e-02]
  [9.18178230e-01]
  [9.64878604e-01]]

 ...

 [[9.81088389e-01]
  [9.73369332e-01]
  [9.61019076e-01]
  ...
  [9.66422337e-01]
  [9.79930687e-01]
  [9.61405107e-01]]

 [[9.73369332e-01]
  [9.61019076e-01]
  [9.81088389e-01]
  ...
  [9.79930687e-01]
  [9.61405107e-01]
  [9.76457190e-01]]

 [[9.61019076e-01]
  [9.81088389e-01]
  [9.83790216e-01]
  ...
  [9.61405107e-01]
  [9.76457190e-01]
  [9.15476796e-01]]]

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

regressor = Sequential()

regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))

regressor.add(Dense(units = 1))

regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

regressor.fit(X_train, y_train, epochs = 100, batch_size = 32)

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:148: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3733: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1020: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3005: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Epoch 1/100
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:190: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:197: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:207: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:216: The name tf.is_variable_initialized is deprecated. Please use tf.compat.v1.is_variable_initialized instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:223: The name tf.variables_initializer is deprecated. Please use tf.compat.v1.variables_initializer instead.

1975/1975 [==============================] - 13s 7ms/step - loss: 0.1264
Epoch 2/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0593
Epoch 3/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0556
Epoch 4/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0578
Epoch 5/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0569
Epoch 6/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0548
Epoch 7/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0577
Epoch 8/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0546
Epoch 9/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0556
Epoch 10/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0543
Epoch 11/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0542
Epoch 12/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0538
Epoch 13/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0549
Epoch 14/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0551
Epoch 15/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0539
Epoch 16/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0546
Epoch 17/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0539
Epoch 18/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0547
Epoch 19/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0545
Epoch 20/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0534
Epoch 21/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0531
Epoch 22/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0536
Epoch 23/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0534
Epoch 24/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0535
Epoch 25/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0543
Epoch 26/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0542
Epoch 27/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0536
Epoch 28/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0537
Epoch 29/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0522
Epoch 30/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0523
Epoch 31/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0529
Epoch 32/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0526
Epoch 33/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0522
Epoch 34/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0527
Epoch 35/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0518
Epoch 36/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0523
Epoch 37/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0524
Epoch 38/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0528
Epoch 39/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0523
Epoch 40/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0524
Epoch 41/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0527
Epoch 42/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0529
Epoch 43/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0519
Epoch 44/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0518
Epoch 45/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0521
Epoch 46/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0520
Epoch 47/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0522
Epoch 48/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0523
Epoch 49/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0522
Epoch 50/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0522
Epoch 51/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0511
Epoch 52/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0510
Epoch 53/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0521
Epoch 54/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0511
Epoch 55/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0513
Epoch 56/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0519
Epoch 57/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0518
Epoch 58/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0520
Epoch 59/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0523
Epoch 60/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0510
Epoch 61/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0513
Epoch 62/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0510
Epoch 63/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0520
Epoch 64/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0521
Epoch 65/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0513
Epoch 66/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0516
Epoch 67/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0518
Epoch 68/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0511
Epoch 69/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0509
Epoch 70/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0522
Epoch 71/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0510
Epoch 72/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0511
Epoch 73/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0509
Epoch 74/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0509
Epoch 75/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0512
Epoch 76/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0509
Epoch 77/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0507
Epoch 78/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0506
Epoch 79/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0509
Epoch 80/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0503
Epoch 81/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0507
Epoch 82/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0505
Epoch 83/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0514
Epoch 84/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0515
Epoch 85/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0512
Epoch 86/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0500
Epoch 87/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0504
Epoch 88/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0508
Epoch 89/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0510
Epoch 90/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0509
Epoch 91/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0513
Epoch 92/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0502
Epoch 93/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0505
Epoch 94/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0511
Epoch 95/100
1975/1975 [==============================] - 11s 5ms/step - loss: 0.0502
Epoch 96/100
1975/1975 [==============================] - 11s 6ms/step - loss: 0.0504
Epoch 97/100
1472/1975 [=====================>........] - ETA: 2s - loss: 0.0515

KeyboardInterrupt: ignored

In [0]:
X_test.head()

In [0]:
dataset_total = pd.concat((X['sensor_00'], X_test['sensor_00']), axis = 0)
print(dataset_total)
inputs = dataset_total[len(dataset_total) - len(X) - 60:].values
inputs = inputs.reshape(-1,1)
#inputs = sc.transform(inputs)
X_test = []
for i in range(60, 76):
    X_test.append(inputs[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = regressor.predict(X_test)
#predicted_stock_price = sc.inverse_transform(predicted_stock_price)
print(predicted_stock_price)