In [0]:
%tensorflow_version 1.x

TensorFlow 1.x selected.

In [0]:
import tensorflow as tf 

tf.test.gpu_device_name()

''

In [0]:
! pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (1.0.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas) (1.18.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import preprocessing
import io

In [0]:
import pandas as pd

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import io 
df2 = pd.read_csv('/content/drive/My Drive/sensor.csv')

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn import preprocessing

In [0]:
train_df = pd.read_csv('/content/drive/My Drive/sensor.csv', header=0)
train_df.drop(train_df.columns[[17]], axis=1, inplace=True)

In [0]:
train_df

        Unnamed: 0            timestamp  ...  sensor_51  machine_status
0                0  2018-04-01 00:00:00  ...   201.3889          NORMAL
1                1  2018-04-01 00:01:00  ...   201.3889          NORMAL
2                2  2018-04-01 00:02:00  ...   203.7037          NORMAL
3                3  2018-04-01 00:03:00  ...   203.1250          NORMAL
4                4  2018-04-01 00:04:00  ...   201.3889          NORMAL
...            ...                  ...  ...        ...             ...
220315      220315  2018-08-31 23:55:00  ...   231.1921          NORMAL
220316      220316  2018-08-31 23:56:00  ...   231.1921          NORMAL
220317      220317  2018-08-31 23:57:00  ...   232.0602          NORMAL
220318      220318  2018-08-31 23:58:00  ...   234.0856          NORMAL
220319      220319  2018-08-31 23:59:00  ...   234.0856          NORMAL

[220320 rows x 54 columns]

In [0]:
'''
for i in range(2,54):
  #target = train_df[i]
  target = train_df.iloc[:, i]
  print(target)
  train_df = train_df.assign(InterpolateSLinear=train_df.target.interpolate(method='slinear'))
'''
train_df = train_df.interpolate(method ='linear', limit_direction ='forward') 
train_df['sensor_01'][27200]
#train_df[1]

38.3680534362793

In [0]:
train_df.head()

   Unnamed: 0            timestamp  ...  sensor_51  machine_status
0           0  2018-04-01 00:00:00  ...   201.3889          NORMAL
1           1  2018-04-01 00:01:00  ...   201.3889          NORMAL
2           2  2018-04-01 00:02:00  ...   203.7037          NORMAL
3           3  2018-04-01 00:03:00  ...   203.1250          NORMAL
4           4  2018-04-01 00:04:00  ...   201.3889          NORMAL

[5 rows x 54 columns]

In [0]:
k = 0
for i in range(len(train_df)):
    if(train_df["machine_status"][i] == "BROKEN"):
        print("Hi")
        count = 0
        for j in range(i,k-1,-1):
            train_df.at[j,'RUL']= count
            count = count + 1
        k = i

Hi
Hi
Hi
Hi
Hi
Hi
Hi

In [0]:

n = len(train_df)-1
while(train_df["machine_status"][n] != "BROKEN"):
    n -= 1   
train_df = train_df[:n+1]        
train_df["machine_status"][n+1] = 0

In [0]:
train_df

        Unnamed: 0            timestamp  ...  machine_status      RUL
0                0  2018-04-01 00:00:00  ...          NORMAL  17155.0
1                1  2018-04-01 00:01:00  ...          NORMAL  17154.0
2                2  2018-04-01 00:02:00  ...          NORMAL  17153.0
3                3  2018-04-01 00:03:00  ...          NORMAL  17152.0
4                4  2018-04-01 00:04:00  ...          NORMAL  17151.0
...            ...                  ...  ...             ...      ...
166436      166436  2018-07-25 13:56:00  ...          NORMAL      4.0
166437      166437  2018-07-25 13:57:00  ...          NORMAL      3.0
166438      166438  2018-07-25 13:58:00  ...          NORMAL      2.0
166439      166439  2018-07-25 13:59:00  ...          NORMAL      1.0
166440      166440  2018-07-25 14:00:00  ...          BROKEN      0.0

[166441 rows x 55 columns]

In [0]:
train_df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [0]:
train_df.head()

             timestamp  sensor_00  sensor_01  ...  sensor_51  machine_status      RUL
0  2018-04-01 00:00:00   2.465394   47.09201  ...   201.3889          NORMAL  17155.0
1  2018-04-01 00:01:00   2.465394   47.09201  ...   201.3889          NORMAL  17154.0
2  2018-04-01 00:02:00   2.444734   47.35243  ...   203.7037          NORMAL  17153.0
3  2018-04-01 00:03:00   2.460474   47.09201  ...   203.1250          NORMAL  17152.0
4  2018-04-01 00:04:00   2.445718   47.13541  ...   201.3889          NORMAL  17151.0

[5 rows x 54 columns]

In [0]:
train_df.drop(['machine_status'], axis=1, inplace=True)

In [0]:
train_df

                  timestamp  sensor_00  ...  sensor_51      RUL
0       2018-04-01 00:00:00   2.465394  ...   201.3889  17155.0
1       2018-04-01 00:01:00   2.465394  ...   201.3889  17154.0
2       2018-04-01 00:02:00   2.444734  ...   203.7037  17153.0
3       2018-04-01 00:03:00   2.460474  ...   203.1250  17152.0
4       2018-04-01 00:04:00   2.445718  ...   201.3889  17151.0
...                     ...        ...  ...        ...      ...
166436  2018-07-25 13:56:00   2.313889  ...   198.2060      4.0
166437  2018-07-25 13:57:00   2.315856  ...   202.8356      3.0
166438  2018-07-25 13:58:00   2.322743  ...   206.8866      2.0
166439  2018-07-25 13:59:00   2.315856  ...   209.7801      1.0
166440  2018-07-25 14:00:00   2.318808  ...   205.7292      0.0

[166441 rows x 53 columns]

In [0]:
train_df.drop(['timestamp'], axis=1, inplace=True)
# from sklearn.decomposition import PCA

# train_df_pca = train_df
# print(train_df['RUL'])
# rul_pca = train_df_pca['RUL']
# print(rul_pca.head()) 
# train_df_pca.drop(['timestamp'], axis=1, inplace=True)
# #print(train_df_pca.head())
# train_df_pca.drop(['RUL'], axis=1, inplace=True)
# pca = PCA(n_components= 20)
# pca_data = pca.fit_transform(train_df_pca.values)
# print(pca_data[0])

In [0]:
len(train_df)

166441

In [0]:
n_features = 51
n_steps = 10

In [0]:
# from sklearn.model_selection import train_test_split
# from numpy.random import seed
# Y = train_df['RUL']
# X = train_df.iloc[:, 0:51]
# X.head()
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.6, random_state = seed(20))

In [0]:
# X_train.shape

(99864, 51)

In [0]:
# X_train= X_train.values.reshape(len(X_train), n_steps, n_features)
# X_test= X_test.values.reshape(len(X_test), n_steps, n_features)

In [0]:
# X_train.shape

(99864, 1, 51)

In [0]:
# from numpy import array
# from numpy import hstack
# from keras.models import Sequential
# from keras.layers import LSTM
# from keras.layers import Dense, Dropout
# from keras.optimizers import SGD
# from keras.layers import BatchNormalization
# from keras.regularizers import l1

# n_features = X_train.shape[2]
# # define model
# model = Sequential()
# model.add(LSTM(100, activation='relu', input_shape=(n_steps, n_features)))
# # model.add(LSTM(50, activation='relu'))
# model.add(Dense(1,activation='linear'))
# opt = SGD(lr=0.005, momentum=0.9, clipnorm=1.0, clipvalue=5.0)
# model.compile(loss='mean_squared_error', optimizer=opt)
# # model.compile(optimizer='adam', loss='mse',
#              # metrics=['accuracy'])
# # fit model
# model.fit(X_train, Y_train, epochs=10, verbose=1)

Using TensorFlow backend.

NameError: ignored

In [0]:
# multivariate data preparation
from numpy import array
from numpy import hstack

# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

# define input sequence
#print(pca_data.shape)
#print(rul_pca.values.shape)
# rul_pca = rul_pca.values.reshape(220320,1)
dataset = train_df.values
# dataset = np.concatenate((pca_data,rul_pca),axis=1)
print('===================================',dataset)
# dataset2 = (dataset[~np.isnan(dataset).any(axis=1)])
#print(dataset)
# choose a number of time steps
n_steps = 10
# convert into input/output
X, y = split_sequences(dataset, n_steps)
#X, y = split_sequences(, n_steps)
print(X.shape, y.shape)
# summarize the data
# for i in range(len(X)):
# 	print(X[i], y[i])

=================================== [[2.46539400e+00 4.70920100e+01 5.32118000e+01 ... 2.43055600e+02
  2.01388900e+02 1.71550000e+04]
 [2.46539400e+00 4.70920100e+01 5.32118000e+01 ... 2.43055600e+02
  2.01388900e+02 1.71540000e+04]
 [2.44473400e+00 4.73524300e+01 5.32118000e+01 ... 2.41319400e+02
  2.03703700e+02 1.71530000e+04]
 ...
 [2.32274300e+00 4.58333300e+01 5.29947900e+01 ... 1.00000000e+03
  2.06886600e+02 2.00000000e+00]
 [2.31585600e+00 4.57899300e+01 5.30381900e+01 ... 1.00000000e+03
  2.09780100e+02 1.00000000e+00]
 [2.31880800e+00 4.58333321e+01 5.29947900e+01 ... 1.00000000e+03
  2.05729200e+02 0.00000000e+00]]
(166432, 10, 51) (166432,)

In [0]:

X_train, X_test, Y_train, Y_test = train_test_split(X, y, train_size = 0.6, random_state = seed(20))
print(X_train)
print("=================================")
print(Y_train)

[[[2.49982600e+00 4.60503500e+01 5.32552100e+01 ... 6.10532400e+01
   1.00000000e+03 1.84317100e+02]
  [2.51064800e+00 4.60937500e+01 5.33854100e+01 ... 5.96064800e+01
   1.00000000e+03 1.84027800e+02]
  [2.49982600e+00 4.60937500e+01 5.33420100e+01 ... 5.81597214e+01
   1.00000000e+03 1.83449100e+02]
  ...
  [2.51064800e+00 4.60503500e+01 5.33854100e+01 ... 5.26620400e+01
   1.00000000e+03 1.75636600e+02]
  [2.49982600e+00 4.61805500e+01 5.33854141e+01 ... 5.23726800e+01
   1.00000000e+03 1.72453700e+02]
  [2.51064800e+00 4.61805500e+01 5.33854100e+01 ... 5.17939800e+01
   1.00000000e+03 1.68981500e+02]]

 [[8.52297861e-02 3.95833321e+01 3.91493034e+01 ... 3.29861107e+01
   3.38541679e+01 1.00000000e+03]
  [8.52108451e-02 3.95833321e+01 3.91493034e+01 ... 3.29861107e+01
   3.38541679e+01 1.00000000e+03]
  [8.51919042e-02 3.95833300e+01 3.91493000e+01 ... 3.29861107e+01
   3.38541679e+01 1.00000000e+03]
  ...
  [8.50971994e-02 3.95399284e+01 3.92361107e+01 ... 3.29861107e+01
   3.38541679e+01 1.00000000e+03]
  [8.50782584e-02 3.95399284e+01 3.92361107e+01 ... 3.29861107e+01
   3.38541679e+01 1.00000000e+03]
  [8.50593174e-02 3.95399300e+01 3.92361107e+01 ... 3.29861107e+01
   3.38541679e+01 1.00000000e+03]]

 [[2.39259300e+00 4.51388900e+01 5.02170100e+01 ... 4.83217600e+01
   1.95601900e+02 1.78530100e+02]
  [2.39652800e+00 4.51388900e+01 5.02170100e+01 ... 4.80324100e+01
   1.95023100e+02 1.77662000e+02]
  [2.40735000e+00 4.50954900e+01 5.03038200e+01 ... 4.77430600e+01
   1.95023100e+02 1.76504600e+02]
  ...
  [2.40735000e+00 4.50954900e+01 5.02170100e+01 ... 4.77430600e+01
   1.97916700e+02 1.72743100e+02]
  [2.39554400e+00 4.50954900e+01 5.02170100e+01 ... 4.74537000e+01
   1.95312500e+02 1.73321800e+02]
  [2.39652800e+00 4.51388900e+01 5.01736100e+01 ... 4.74537000e+01
   1.92129600e+02 1.72743100e+02]]

 ...

 [[2.35225700e+00 4.35763900e+01 4.76128500e+01 ... 4.48495400e+01
   1.78240700e+02 1.76215300e+02]
  [2.35619200e+00 4.34895800e+01 4.75694400e+01 ... 4.48495400e+01
   1.76215300e+02 1.69849500e+02]
  [2.35127300e+00 4.35763900e+01 4.76128500e+01 ... 4.45601800e+01
   1.72743100e+02 1.64641200e+02]
  ...
  [2.35816000e+00 4.34895800e+01 4.75694427e+01 ... 4.36921300e+01
   1.59432900e+02 1.58854200e+02]
  [2.34832200e+00 4.34895800e+01 4.75694427e+01 ... 4.34027786e+01
   1.58275500e+02 1.59722200e+02]
  [2.35520800e+00 4.34895800e+01 4.75694427e+01 ... 4.31134300e+01
   1.57407400e+02 1.59722200e+02]]

 [[2.44079900e+00 4.67447900e+01 5.28211784e+01 ... 8.56481500e+01
   2.92245400e+02 2.44213000e+02]
  [2.42997700e+00 4.68750000e+01 5.28211784e+01 ... 8.79629600e+01
   2.87615800e+02 2.45949100e+02]
  [2.43883100e+00 4.68316000e+01 5.28211784e+01 ... 8.94097200e+01
   2.84722200e+02 2.47106500e+02]
  ...
  [2.44079900e+00 4.68750000e+01 5.28211800e+01 ... 8.59375000e+01
   2.80960600e+02 2.46527800e+02]
  [2.43096100e+00 4.68750000e+01 5.29079900e+01 ... 8.65162000e+01
   2.81828700e+02 2.47106500e+02]
  [2.44079900e+00 4.68750000e+01 5.28211800e+01 ... 8.53588000e+01
   2.83564800e+02 2.47685200e+02]]

 [[2.45162000e+00 4.96527700e+01 5.32552100e+01 ... 4.77430573e+01
   1.74768500e+02 1.75057900e+02]
  [2.45949100e+00 4.96527700e+01 5.32552100e+01 ... 4.77430573e+01
   1.75057900e+02 1.77662000e+02]
  [2.45162000e+00 4.96961800e+01 5.32552100e+01 ... 4.77430600e+01
   1.75057900e+02 1.81134300e+02]
  ...
  [2.45555600e+00 5.00868000e+01 5.32552100e+01 ... 4.68750000e+01
   1.74768500e+02 1.80844900e+02]
  [2.45457200e+00 4.99566000e+01 5.33420100e+01 ... 4.68750000e+01
   1.74768500e+02 1.75636600e+02]
  [2.45162000e+00 4.99131900e+01 5.33420105e+01 ... 4.65856500e+01
   1.74189800e+02 1.70717600e+02]]]
=================================
[ 3495. 10619.  4982. ...   726. 32174. 35397.]

In [0]:
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense, Dropout
from keras.optimizers import SGD
from keras.layers import BatchNormalization
from keras.regularizers import l1

n_features = X_train.shape[2]
# define model
model = Sequential()
model.add(LSTM(128, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(64, activation='relu'))
model.add(Dense(1,activation='linear'))
opt = SGD(lr=0.001, momentum=0.9, clipnorm=1.0, clipvalue=5.0)
model.compile(loss='mean_squared_error', optimizer=opt)
# model.compile(optimizer='adam', loss='mse',
             # metrics=['accuracy'])
# fit model
history = model.fit(X_train, Y_train, validation_split=0.25, epochs=100, verbose=1)
# demonstrate prediction
#yhat = model.predict(X_test, verbose=0)
#print(yhat)

Train on 74894 samples, validate on 24965 samples
Epoch 1/100
74894/74894 [==============================] - 44s 589us/step - loss: 221990333.2462 - val_loss: 152956414.5234
Epoch 2/100
74894/74894 [==============================] - 45s 596us/step - loss: 172136337.2459 - val_loss: 147105184.9960
Epoch 3/100
74894/74894 [==============================] - 43s 580us/step - loss: 136876705.9981 - val_loss: 105746825.6455
Epoch 4/100
74894/74894 [==============================] - 44s 581us/step - loss: 121313860.9410 - val_loss: 108855037.6941
Epoch 5/100
74894/74894 [==============================] - 44s 584us/step - loss: 111514257.6275 - val_loss: 80072459.1612
Epoch 6/100
74894/74894 [==============================] - 43s 572us/step - loss: 94572778.4273 - val_loss: 81202607.6405
Epoch 7/100
74894/74894 [==============================] - 44s 583us/step - loss: 84276928.5207 - val_loss: 85873640.0535
Epoch 8/100
74894/74894 [==============================] - 43s 577us/step - loss: 77722692.8608 - val_loss: 70057114.1640
Epoch 9/100
74894/74894 [==============================] - 45s 597us/step - loss: 73600355.8354 - val_loss: 57849166.2641
Epoch 10/100
74894/74894 [==============================] - 44s 586us/step - loss: 67536295.6243 - val_loss: 54742310.8488
Epoch 11/100
74894/74894 [==============================] - 44s 586us/step - loss: 62905162.4709 - val_loss: 64413407.1989
Epoch 12/100
74894/74894 [==============================] - 44s 587us/step - loss: 57095280.6210 - val_loss: 59699128.4361
Epoch 13/100
74894/74894 [==============================] - 44s 591us/step - loss: 53327490.2653 - val_loss: 42461397.3068
Epoch 14/100
74894/74894 [==============================] - 46s 615us/step - loss: 49184806.2436 - val_loss: 76066264.9767
Epoch 15/100
74894/74894 [==============================] - 45s 602us/step - loss: 43507058.6957 - val_loss: 63240437.8267
Epoch 16/100
74894/74894 [==============================] - 47s 624us/step - loss: 41708628.9130 - val_loss: 29519020.9668
Epoch 17/100
74894/74894 [==============================] - 46s 610us/step - loss: 37259635.4952 - val_loss: 36874939.1708
Epoch 18/100
74894/74894 [==============================] - 46s 608us/step - loss: 37494797.5991 - val_loss: 30556465.4129
Epoch 19/100
74894/74894 [==============================] - 46s 609us/step - loss: 36344928.6697 - val_loss: 51332453.3798
Epoch 20/100
74894/74894 [==============================] - 45s 596us/step - loss: 34671125.3921 - val_loss: 25168838.1229
Epoch 21/100
74894/74894 [==============================] - 45s 597us/step - loss: 32236315.7372 - val_loss: 32927140.4656
Epoch 22/100
74894/74894 [==============================] - 44s 586us/step - loss: 30488165.0348 - val_loss: 27145627.2210
Epoch 23/100
74894/74894 [==============================] - 46s 611us/step - loss: 29939490.7866 - val_loss: 35816214.9049
Epoch 24/100
74894/74894 [==============================] - 45s 604us/step - loss: 28237272.1232 - val_loss: 24441981.5576
Epoch 25/100
74894/74894 [==============================] - 45s 604us/step - loss: 28240040.6446 - val_loss: 21061076.7247
Epoch 26/100
74894/74894 [==============================] - 45s 605us/step - loss: 26595044.0232 - val_loss: 35737562.5048
Epoch 27/100
74894/74894 [==============================] - 48s 644us/step - loss: 25937080.8212 - val_loss: 36470715.0498
Epoch 28/100
74894/74894 [==============================] - 45s 603us/step - loss: 23745914.7855 - val_loss: 21634399.4877
Epoch 29/100
74894/74894 [==============================] - 46s 608us/step - loss: 25359520.5032 - val_loss: 16987968.7718
Epoch 30/100
74894/74894 [==============================] - 46s 618us/step - loss: 24644619.3952 - val_loss: 26191163.3356
Epoch 31/100
74894/74894 [==============================] - 46s 611us/step - loss: 23274465.7294 - val_loss: 24316422.1206
Epoch 32/100
74894/74894 [==============================] - 46s 608us/step - loss: 22313840.1186 - val_loss: 26265126.2850
Epoch 33/100
74894/74894 [==============================] - 46s 615us/step - loss: 22048377.4161 - val_loss: 17837359.6849
Epoch 34/100
74894/74894 [==============================] - 47s 623us/step - loss: 20808336.7136 - val_loss: 15766304.2580
Epoch 35/100
74894/74894 [==============================] - 46s 611us/step - loss: 20390729.1835 - val_loss: 19580391.2454
Epoch 36/100
74894/74894 [==============================] - 46s 620us/step - loss: 19791684.5551 - val_loss: 19782456.9064
Epoch 37/100
74894/74894 [==============================] - 46s 614us/step - loss: 19941207.4901 - val_loss: 21605431.1955
Epoch 38/100
74894/74894 [==============================] - 45s 595us/step - loss: 19312266.5387 - val_loss: 19828354.5659
Epoch 39/100
74894/74894 [==============================] - 45s 599us/step - loss: 18593910.9440 - val_loss: 22595765.2654
Epoch 40/100
74894/74894 [==============================] - 45s 605us/step - loss: 18299163.8841 - val_loss: 19342274.1912
Epoch 41/100
74894/74894 [==============================] - 47s 633us/step - loss: 18039348.3493 - val_loss: 20558267.2343
Epoch 42/100
74894/74894 [==============================] - 44s 594us/step - loss: 18728922.2310 - val_loss: 15849180.5307
Epoch 43/100
74894/74894 [==============================] - 45s 601us/step - loss: 17925389.4384 - val_loss: 16382767.9288
Epoch 44/100
74894/74894 [==============================] - 44s 585us/step - loss: 17865651.6180 - val_loss: 15145030.3380
Epoch 45/100
74894/74894 [==============================] - 44s 586us/step - loss: 17472895.3841 - val_loss: 15658565.2351
Epoch 46/100
74894/74894 [==============================] - 44s 584us/step - loss: 17197549.4755 - val_loss: 15510699.9489
Epoch 47/100
74894/74894 [==============================] - 44s 585us/step - loss: 17324697.3267 - val_loss: 13986157.5531
Epoch 48/100
74894/74894 [==============================] - 44s 588us/step - loss: 15982464.8715 - val_loss: 13221241.4199
Epoch 49/100
74894/74894 [==============================] - 44s 581us/step - loss: 16094601.8385 - val_loss: 15445795.5322
Epoch 50/100
74894/74894 [==============================] - 45s 602us/step - loss: 16156856.7879 - val_loss: 21729942.4777
Epoch 51/100
74894/74894 [==============================] - 44s 583us/step - loss: 15669810.8326 - val_loss: 18337178.1091
Epoch 52/100
74894/74894 [==============================] - 44s 589us/step - loss: 15256432.2893 - val_loss: 14224172.0515
Epoch 53/100
74894/74894 [==============================] - 44s 584us/step - loss: 15146772.1835 - val_loss: 13840560.0859
Epoch 54/100
74894/74894 [==============================] - 44s 589us/step - loss: 15744961.5806 - val_loss: 15985888.1014
Epoch 55/100
74894/74894 [==============================] - 45s 600us/step - loss: 15254190.0378 - val_loss: 15179303.2812
Epoch 56/100
74894/74894 [==============================] - 44s 588us/step - loss: 15262275.9966 - val_loss: 12517475.7055
Epoch 57/100
74894/74894 [==============================] - 45s 601us/step - loss: 14565804.1383 - val_loss: 13371925.5272
Epoch 58/100
74894/74894 [==============================] - 44s 586us/step - loss: 14946308.0886 - val_loss: 27896558.8116
Epoch 59/100
74894/74894 [==============================] - 45s 595us/step - loss: 15839249.9381 - val_loss: 13066184.0602
Epoch 60/100
74894/74894 [==============================] - 44s 589us/step - loss: 15448125.3336 - val_loss: 22513279.1349
Epoch 61/100
74894/74894 [==============================] - 44s 589us/step - loss: 15045081.8369 - val_loss: 13596754.9393
Epoch 62/100
74894/74894 [==============================] - 44s 588us/step - loss: 13879301.2119 - val_loss: 23011848.8116
Epoch 63/100
74894/74894 [==============================] - 44s 585us/step - loss: 15383366.0741 - val_loss: 16140547.6174
Epoch 64/100
74894/74894 [==============================] - 45s 598us/step - loss: 13763354.0426 - val_loss: 11898024.5268
Epoch 65/100
74894/74894 [==============================] - 44s 584us/step - loss: 15455102.8943 - val_loss: 20191767.1243
Epoch 66/100
74894/74894 [==============================] - 44s 594us/step - loss: 13833349.5876 - val_loss: 10773380.4625
Epoch 67/100
74894/74894 [==============================] - 45s 606us/step - loss: 13342487.5528 - val_loss: 20362788.4400
Epoch 68/100
74894/74894 [==============================] - 46s 614us/step - loss: 13474091.9754 - val_loss: 13548150.1120
Epoch 69/100
74894/74894 [==============================] - 46s 613us/step - loss: 13251532.4940 - val_loss: 10396492.3345
Epoch 70/100
74894/74894 [==============================] - 46s 608us/step - loss: 13461854.7687 - val_loss: 19261358.1958
Epoch 71/100
74894/74894 [==============================] - 45s 602us/step - loss: 12875073.4336 - val_loss: 12380661.6527
Epoch 72/100
74894/74894 [==============================] - 45s 596us/step - loss: 13147628.6924 - val_loss: 10235263.3022
Epoch 73/100
74894/74894 [==============================] - 45s 599us/step - loss: 12403546.1756 - val_loss: 12664020.4612
Epoch 74/100
74894/74894 [==============================] - 45s 607us/step - loss: 12669287.3541 - val_loss: 9833364.7046
Epoch 75/100
74894/74894 [==============================] - 46s 609us/step - loss: 12587793.0857 - val_loss: 11325349.5174
Epoch 76/100
74894/74894 [==============================] - 45s 604us/step - loss: 12912982.8400 - val_loss: 14889880.5022
Epoch 77/100
74894/74894 [==============================] - 46s 609us/step - loss: 12430803.7413 - val_loss: 11104125.9759
Epoch 78/100
74894/74894 [==============================] - 46s 619us/step - loss: 12059463.9188 - val_loss: 16069203.3457
Epoch 79/100
74894/74894 [==============================] - 46s 617us/step - loss: 11781364.6370 - val_loss: 11858048.7497
Epoch 80/100
74894/74894 [==============================] - 45s 604us/step - loss: 12134463.5865 - val_loss: 15651986.2384
Epoch 81/100
74894/74894 [==============================] - 46s 610us/step - loss: 13043084.7123 - val_loss: 27835180.6276
Epoch 82/100
74894/74894 [==============================] - 46s 615us/step - loss: 11710651.6820 - val_loss: 9970402.4965
Epoch 83/100
74894/74894 [==============================] - 46s 608us/step - loss: 12321029.0556 - val_loss: 15123722.6622
Epoch 84/100
74894/74894 [==============================] - 46s 610us/step - loss: 12356956.4566 - val_loss: 12451515.9389
Epoch 85/100
74894/74894 [==============================] - 46s 619us/step - loss: 12303452.5724 - val_loss: 10380522.4580
Epoch 86/100
74894/74894 [==============================] - 45s 607us/step - loss: 10704064.2065 - val_loss: 13967304.5233
Epoch 87/100
74894/74894 [==============================] - 45s 607us/step - loss: 10981981.3705 - val_loss: 12407543.2961
Epoch 88/100
74894/74894 [==============================] - 46s 608us/step - loss: 11349809.3212 - val_loss: 16477660.4337
Epoch 89/100
74894/74894 [==============================] - 46s 610us/step - loss: 12600749.0198 - val_loss: 8477257.4779
Epoch 90/100
74894/74894 [==============================] - 45s 604us/step - loss: 11070436.9667 - val_loss: 10866249.2259
Epoch 91/100
74894/74894 [==============================] - 46s 608us/step - loss: 10973394.0564 - val_loss: 12419723.9343
Epoch 92/100
74894/74894 [==============================] - 46s 616us/step - loss: 11550973.4470 - val_loss: 10521576.5653
Epoch 93/100
74894/74894 [==============================] - 45s 603us/step - loss: 11441273.8754 - val_loss: 10498818.1882
Epoch 94/100
74894/74894 [==============================] - 46s 611us/step - loss: 11715199.8116 - val_loss: 10284086.9087
Epoch 95/100
74894/74894 [==============================] - 47s 629us/step - loss: 11020437.4187 - val_loss: 10011812.0191
Epoch 96/100
74894/74894 [==============================] - 46s 615us/step - loss: 10982136.6078 - val_loss: 8843798.3894
Epoch 97/100
74894/74894 [==============================] - 45s 605us/step - loss: 11664624.6863 - val_loss: 10772590.5202
Epoch 98/100
74894/74894 [==============================] - 46s 616us/step - loss: 10856515.7301 - val_loss: 9017741.3430
Epoch 99/100
74894/74894 [==============================] - 45s 602us/step - loss: 10431369.5226 - val_loss: 10171374.3198
Epoch 100/100
74894/74894 [==============================] - 45s 607us/step - loss: 11293287.5404 - val_loss: 10717131.0244

In [0]:
y_pred = model.predict(X_test, verbose=0)

In [0]:
import matplotlib.pyplot as plt

plt.plot(history.history['val_acc'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Test'], loc='upper left')
plt.show()

KeyError: ignored

In [0]:
print(y_pred)

[[21838.836 ]
 [26295.361 ]
 [ 5915.1377]
 ...
 [25982.025 ]
 [ 1844.6945]
 [21930.49  ]]

In [0]:
print(Y_test)

[23527. 28063.  6607. ... 28939.  3257. 19258.]

In [0]:
from sklearn.metrics import r2_score
r2_score(Y_test, y_pred)

0.9440189158992123

In [0]:
import pickle
from google.colab import files

In [0]:
filename = 'lstm_reg3_modelEPOCHS10.sav'
pickle.dump(model, open(filename, 'wb'))

In [0]:
files.download('lstm_reg3_modelEPOCHS10.sav')

In [0]:
# multivariate multi-step stacked lstm example
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense, Dropout


n_features = X_train.shape[2]
# define model
model = Sequential()
model.add(LSTM(100, activation='relu', return_sequences=False, input_shape=(n_steps, n_features)))
model.add(Dense(100, activation='relu'))
model.add(Dense(1,kernel_initializer='normal',activation='relu'))
model.compile(optimizer='adam', loss='mse')
# fit model
history= model.fit(X_train, Y_train, validation_split=0.25, epochs=100, verbose=1)
# demonstrate prediction
yhat = model.predict(X_test, verbose=0)
print(yhat)

RuntimeError: ignored

In [0]:
Y_test

In [0]:
import pickle
from google.colab import files

In [0]:
filename = 'lstm_bin_modelEPOCH10.sav'
pickle.dump(model, open(filename, 'wb'))

In [0]:
files.download('lstm_bin_modelEPOCH10.sav')